/* Campaign definitions and validation, independent of rendering. */
(function(root){'use strict';const quests={
 trail:{npc:'aya',title:'Além da primeira ponte',text:'As pontes ao norte levam a uma fronteira esquecida. Alcance o acampamento central da primeira faixa e volte para registrar sua descoberta.',goal:1,reward:120,coins:80,item:['weapon',2,'rare']},
 hunt:{npc:'ren',requires:'trail',title:'A trilha dos viajantes',text:'As criaturas impedem nossa passagem. Derrote seis inimigos da fronteira. Feitos anteriores também contam. Volte para receber vestes de viagem.',goal:6,reward:220,coins:110,item:['robe',3,'rare']},
 lights:{npc:'noor',requires:'hunt',title:'Três luzes na geada',text:'Acenda os faróis das três ilhas da segunda faixa. Eles ficam perto do centro de cada ilha. Aproxime-se e pressione E.',goal:3,reward:280,coins:160,item:['weapon',5,'rare']},
 trial:{npc:'hana',requires:'lights',title:'A prova dos cinco ecos',text:'Enfrente três ondas na arena deste acampamento: duas feras, dois espíritos e um guardião. Você pode tentar novamente sem perder seus itens.',goal:1,reward:350,coins:220,item:['amulet',7,'rare']},
 crown:{npc:'sora',requires:'trial',title:'A última sombra',text:'Um dos três colossos da última faixa guarda a origem da névoa. Derrote qualquer um deles e retorne. Sua arma final será forjada com a luz recuperada.',goal:1,reward:500,coins:350,item:['weapon',9,'epic']}
};
function clean(raw,oldEnemies=[]){const s=raw&&typeof raw==='object'?raw:{},num=(x,max,d=0)=>Number.isFinite(x)?Math.floor(Math.max(0,Math.min(max,x))):d,ids=(a,max)=>Array.isArray(a)?[...new Set(a.filter(n=>Number.isInteger(n)&&n>=0&&n<=max))]:[];return {frontierKills:num(s.frontierKills,1e7,oldEnemies.filter(e=>e.id>=100&&!e.alive).length),eliteKills:num(s.eliteKills,1e7,oldEnemies.filter(e=>[291,311,331].includes(e.id)&&!e.alive).length),beacons:ids(s.beacons,2),chests:ids(s.chests,11),trialWon:s.trialWon===true,tracked:Object.hasOwn(quests,s.tracked)?s.tracked:null};}
function upgradePlan(S,bag,level){const old=S.byId(bag.equipped.weapon);if(!old)return {error:'Equipe uma arma antes de usar a forja.'};if(old.tier>=12)return {error:'Esta arma já atingiu o grau máximo.'};const next=S.item(old.key,old.tier+1,old.rarity);if(next.required>level)return {error:'Alcance o nível '+next.required+' para melhorar esta arma.'};const coins=35+next.tier*20,shards=1+Math.ceil(next.tier/3),source=bag.items.find(i=>i.id===old.id);if(!source)return {error:'A arma equipada não foi encontrada.'};if((bag.items.find(i=>i.id===next.id)?.qty||0)>=999)return {error:'A pilha da arma melhorada já está cheia.'};const full=bag.items.length>=60&&!bag.items.some(i=>i.id===next.id)&&source.qty>1;if(full)return {error:'Libere um espaço na mochila para a arma melhorada.'};return {old,next,coins,shards,ready:bag.coins>=coins&&(bag.items.find(i=>i.id==='shard:0:common')?.qty||0)>=shards};}
const api={quests,clean,upgradePlan};root.JadeCampaign=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
