const assert=require('node:assert/strict'),S=require('./systems.js'),E=require('./economy.js'),Storage=require('./storage.js');
const now=1800000000000,make=()=>({version:3,slots:[Storage.cleanSlot({id:'a',name:'Jade',classId:'sword',state:{inventory:{...S.starter('sword'),coins:1000}}}),Storage.cleanSlot({id:'b',name:'Lua',classId:'mage',state:{inventory:{...S.starter('mage'),coins:200}}}),null]});
let data=make(),original=JSON.stringify(data),r=E.run(data,0,{type:'buy',region:0,id:'tea:0:common',qty:8},now);assert.equal(JSON.stringify(data),original);assert.equal(r.data.slots[0].state.inventory.coins,856);assert.throws(()=>E.run(r.data,1,{type:'buy',region:0,id:'tea:0:common',qty:1},now),/Estoque/);assert.equal(E.offers(0,'sword',E.current(r.data.economy,now+E.PERIOD))[3].stock,8);
r=E.run(r.data,0,{type:'sell',region:3,id:'tea:0:common',qty:8},now);assert.equal(r.data.slots[0].state.inventory.coins,1096);assert.equal(r.data.economy.history.length,2);
for(let region=0;region<5;region++)for(const rep of [0,100])for(const offer of E.offers(region,'summoner',E.current(null,now)))assert(E.price(offer.it.id,region,'buy',rep)>E.price(offer.it.id,region,'sell',rep));
const trade={type:'trade',target:1,give:{id:'health:0:common',qty:2,coins:150},take:{id:'mana:0:common',qty:1,coins:20}};r=E.run(data,0,trade,now);assert.equal(r.data.slots[0].state.inventory.coins,870);assert.equal(r.data.slots[1].state.inventory.coins,330);assert.equal(r.data.slots[0].state.inventory.items.find(i=>i.id==='health:0:common').qty,1);assert.equal(r.data.slots[1].state.inventory.items.find(i=>i.id==='health:0:common').qty,5);
assert.throws(()=>E.run(data,0,{...trade,give:{id:'sword:0:common',qty:1,coins:0}},now),/equipada/);assert.throws(()=>E.run(data,0,{...trade,give:{coins:1001}},now),/Moedas/);assert.throws(()=>E.run(data,0,{...trade,target:0},now),/outro/);
for(const qty of [-1,0,1.5,1000,NaN])assert.throws(()=>E.run(data,0,{type:'buy',region:0,id:'health:0:common',qty},now));
const full=make();full.slots[1].state.inventory.items=[];for(let t=0;t<12;t++)for(const key of ['sword','robe','staff','amulet','spear'])full.slots[1].state.inventory.items.push({id:S.item(key,t,'rare').id,qty:1});assert.equal(full.slots[1].state.inventory.items.length,60);assert.throws(()=>E.run(full,0,{...trade,take:{coins:0}},now),/espaço/);assert.equal(full.slots[0].state.inventory.coins,1000);
const stacked=make();stacked.slots[1].state.inventory.items.find(i=>i.id==='health:0:common').qty=999;assert.throws(()=>E.run(stacked,0,trade,now),/espaço/);
const cap=make();cap.slots[0].state.inventory.coins=9999999;assert.throws(()=>E.run(cap,0,{type:'sell',region:0,id:'health:0:common',qty:1},now),/Limite/);
const orders=make();orders.slots[0].state.inventory.items.push({id:'shard:0:common',qty:20});r=E.run(orders,0,{type:'order',region:0},now);assert.equal(r.data.economy.reputation,5);assert.equal(r.data.slots[0].state.inventory.coins,1090);assert.throws(()=>E.run(r.data,0,{type:'order',region:0},now),/já entregue/);assert.equal(E.current(r.data.economy,now+E.PERIOD).orders.length,0);
const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},store=new Storage.CharacterStore(storage);assert(store.commit(r.data));const saved=store.export();assert.equal(new Storage.CharacterStore(storage).data.economy.reputation,5);storage.setItem=()=>{throw Error('quota');};assert.equal(store.commit(E.run(r.data,0,trade,now).data),false);assert.equal(store.export(),saved);assert.equal(memory.get(Storage.KEY),JSON.stringify(store.data));
assert.equal(Storage.parse(JSON.stringify(make())).economy.reputation,0);assert.equal(Storage.parse(saved).slots[0].state.inventory.items.find(i=>i.id==='shard:0:common').qty,15);
console.log('PASS economy: price spreads, profitable routes, shared stock and restock, two-sided conservation, equipped protection, invalid amounts, capacity/stack/coin limits, orders once, legacy saves and atomic rollback on storage failure.');

