/* Vale de Jade — original procedural art and solo gameplay. Three.js r160 / MIT. */
(()=>{'use strict';
const $=s=>document.getElementById(s),T=THREE;
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('introText').textContent='Não foi possível iniciar o 3D. Abra no Chrome ou Edge com aceleração gráfica ativada.';$('start').hidden=true;return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;$('world').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#aec9c6');scene.fog=new T.FogExp2('#aec9c6',.008);
const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.08,280),clock=new T.Clock();
scene.add(new T.HemisphereLight(0xfff4d9,0x658c83,1.7));const sun=new T.DirectionalLight(0xffe9c5,2.1);sun.position.set(-22,40,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:110});sun.shadow.bias=-.001;scene.add(sun);
const mats=new Map();function mat(c){if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.82,metalness:.02}));return mats.get(c);}
function mesh(g,c,x=0,y=0,z=0,parent=scene){const m=new T.Mesh(g,typeof c==='string'||typeof c==='number'?mat(c):c);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,c,x,y,z,p){return mesh(new T.BoxGeometry(w,h,d),c,x,y,z,p);}function ball(r,c,x,y,z,p,s=1){const m=mesh(new T.IcosahedronGeometry(r,2),c,x,y,z,p);m.scale.y=s;return m;}
function cyl(rt,rb,h,c,x,y,z,p,n=10){return mesh(new T.CylinderGeometry(rt,rb,h,n),c,x,y,z,p);}function ring(r,c,x,z,y=.07){const m=mesh(new T.RingGeometry(r-.035,r,64),new T.MeshBasicMaterial({color:c,transparent:true,opacity:.7,side:T.DoubleSide}),x,y,z);m.rotation.x=-Math.PI/2;return m;}
let seed=42;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const between=(a,b)=>a+rnd()*(b-a);
const floor=cyl(37,34,2.5,'#89a47a',0,-1.35,0,scene,80);cyl(34,26,9,'#688982',0,-7,0,scene,32);
const cameraOccluders=[];const obstacles=[];function obstacle(x,z,r){obstacles.push({x,z,r});}
// Stone walkways and the engraved central cultivation court.
for(let i=-15;i<=14;i++){let z=i*1.9;for(let j=-1;j<=1;j++){const b=box(1.72,.1,1.75,(i+j)%3===0?'#bdc1a5':'#ccd0b5',j*1.86,.015,z);b.rotation.y=between(-.025,.025);}}
cyl(6.1,6.1,.13,'#c4cbb0',0,.06,4,scene,64);for(const r of [4.3,4.5,5.6])ring(r,'#819d8a',0,4,.14);
for(let i=0;i<8;i++){let a=i*Math.PI/4;const b=box(.22,.03,1,'#8ca591',Math.sin(a)*5,.15,4+Math.cos(a)*5);b.rotation.y=a;}
// Pond, lotus leaves and an arched footbridge.
const pond=mesh(new T.CircleGeometry(7.4,64),new T.MeshPhongMaterial({color:'#59a6a3',transparent:true,opacity:.83,shininess:90}),-13,.04,3);pond.rotation.x=-Math.PI/2;pond.scale.y=.7;
for(let i=0;i<32;i++){const a=i/32*Math.PI*2;ball(between(.45,.85),'#92aaa0',-13+Math.cos(a)*7.6,.25,3+Math.sin(a)*5.3,scene,.65);}
for(let i=0;i<13;i++){let x=-13+between(-5,5),z=3+between(-3,3);const leaf=cyl(.5,.5,.025,'#548c68',x,.09,z,scene,12);if(i%3===0){for(let j=0;j<5;j++){let a=j*1.256;ball(.17,'#f0c6c9',x+Math.cos(a)*.15,.2,z+Math.sin(a)*.15,scene,1.2);}}}
for(let i=0;i<20;i++){let x=-22+i*.65,y=.3+Math.sin(i/19*Math.PI)*1.05;box(.62,.16,2.4,'#a98361',x,y,3);for(let side of [-1,1]){if(i%3===0)cyl(.08,.09,1.2,'#764f45',x,y+.6,3+side*1.15);box(.67,.1,.1,'#9c6150',x,y+1.13,3+side*1.15);}}
// Stylized multi-tier shrine with swept roof corners.
function roof(w,d,y,p){const verts=[],idx=[];const levels=[{w:w*.13,d:d*.13,y:y+1.25},{w:w*.4,d:d*.4,y:y+.45},{w:w*.5,d:d*.5,y:y+.16},{w:w*.58,d:d*.58,y:y+.5}];for(const l of levels)for(const [a,b] of [[-1,-1],[1,-1],[1,1],[-1,1]])verts.push(a*l.w,l.y,b*l.d);for(let k=0;k<3;k++)for(let j=0;j<4;j++){let a=k*4+j,b=k*4+(j+1)%4;idx.push(a,b,a+4,b,b+4,a+4);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));geo.setIndex(idx);geo.computeVertexNormals();mesh(geo,new T.MeshToonMaterial({color:'#426b64',side:T.DoubleSide}),0,0,0,p);for(let sx of [-1,1])for(let sz of [-1,1])ball(.13,'#d5bc79',sx*w*.58,y+.53,sz*d*.58,p);box(w*.25,.12,.16,'#c2ad77',0,y+1.26,0,p);}
function temple(x,z,scale=1){let p=new T.Group();scene.add(p);p.position.set(x,0,z);p.scale.setScalar(scale);box(8,.45,6,'#a2b2a0',0,.2,0,p);box(7.2,.35,5.2,'#d0ccb0',0,.6,0,p);box(5.7,3.4,3.9,'#e5d9b8',0,2.35,0,p);for(let sx of [-1,1])for(let sz of [-1,1]){cyl(.17,.22,3.8,'#9d5544',sx*3,.1+2,sz*2.05,p);box(.45,.15,.45,'#dfc58a',sx*3,3.65,sz*2.05,p);}box(1.4,2.7,.12,'#4e6260',0,2,2,p);for(let sx of [-1,1]){box(1.25,1.25,.12,'#6f8979',sx*1.9,2.55,2.02,p);for(let j=-1;j<=1;j++)box(.055,1.3,.05,'#d1bd8c',sx*1.9+j*.33,2.55,2.1,p);}roof(8,6,4,p);box(3,1.65,2.6,'#e5d9b8',0,5.8,0,p);roof(5.4,4.6,6.4,p);cyl(.07,.16,1.2,'#c9b071',0,8.1,0,p);ball(.22,'#e0c787',0,8.8,0,p);for(let i=0;i<4;i++)box(3,.15,1,'#c8c8ac',0,.08+i*.12,4-i*.55,p);obstacle(x,z,4*scale);cameraOccluders.push(p);return p;}
temple(0,-23,1.25);temple(19,13,.65);temple(-24,-11,.55);
function gate(x,z){for(let sx of [-1,1]){cyl(.25,.35,5,'#aa6650',x+sx*3,2.5,z);cyl(.5,.5,.3,'#bdbb9b',x+sx*3,.15,z);}box(7.7,.38,.55,'#824c42',x,4.7,z);box(6.8,.3,.55,'#b77354',x,3.8,z);const p=new T.Group();scene.add(p);p.position.set(x,0,z);roof(7.3,1.6,4.9,p);box(1.1,1.05,.16,'#284e47',x,4.1,z+.36);}
gate(0,20);
function tree(x,z,s=1,pink=false){const p=new T.Group();p.position.set(x,0,z);p.scale.setScalar(s);scene.add(p);const trunk=cyl(.2,.4,3.5,'#6b6b53',0,1.75,0,p,7);trunk.rotation.z=.12;for(let j=0;j<3;j++){const b=cyl(.09,.19,2,'#6b6b53',j-1,3,0,p,6);b.rotation.z=(j-1)*-.7;}const colors=pink?['#e8b6bd','#edc6c8','#dca2b1']:['#6e956d','#85a37a','#577e63'];for(let j=0;j<7;j++){let a=j*2.4;ball(between(1.1,1.7),colors[j%3],Math.cos(a)*1.3,3.9+rnd(),Math.sin(a)*1.2,p,.7);}obstacle(x,z,.6*s);cameraOccluders.push(p);}
for(const [x,z,s]of [[-7,13,1.3],[18,22,1.2],[-7,-13,1.4],[8,-16,1.3],[21,-9,1.5],[-25,9,1.2],[14,6,.9]])tree(x,z,s,true);
for(let i=0;i<35;i++){let a=rnd()*6.28,r=between(25,35),x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)<5)continue;tree(x,z,between(.7,1.3),i%5===0);}
function lantern(x,z){cyl(.09,.12,2.2,'#6a6450',x,1.1,z);box(.9,.12,.9,'#5d7364',x,2.6,z);cyl(.36,.3,.62,'#edbd76',x,2.23,z,scene,6);box(.65,.13,.65,'#a49670',x,1.85,z);const glow=ball(.25,new T.MeshBasicMaterial({color:'#ffe5a2'}),x,2.23,z);}
for(let z=-17;z<=20;z+=7){lantern(-3.8,z);lantern(3.8,z);}
// Ground detail and distant floating mountains.
for(let i=0;i<210;i++){let x=between(-33,33),z=between(-33,33);if(Math.hypot(x,z)>34||Math.abs(x)<4||Math.hypot(x,z-4)<6||((x+13)**2/60+(z-3)**2/30)<1)continue;for(let j=0;j<3;j++){const g=mesh(new T.ConeGeometry(.13,.5,3),i%8===0?'#e1c9b0':'#79966e',x+j*.15,.2,z);g.rotation.z=between(-.3,.3);}if(i%12===0)ball(between(.6,1.2),'#93a89a',x,.25,z,scene,.65);}
for(let i=0;i<23;i++){let a=i/23*6.28,r=between(60,100),x=Math.cos(a)*r,z=Math.sin(a)*r,h=between(15,42);const m=cyl(between(2,5),between(5,10),h,i%2?'#7eaaa4':'#92b8af',x,h*.15-10,z,scene,7);ball(5,'#80a791',x,h*.65-10,z,scene,.45);}
// Painted ground, cloud banks, roof ribs and moving water highlights.
const terrainCanvas=document.createElement('canvas');terrainCanvas.width=terrainCanvas.height=1024;const tc=terrainCanvas.getContext('2d');tc.fillStyle='#829565';tc.fillRect(0,0,1024,1024);for(let i=0;i<19000;i++){let x=rnd()*1024,y=rnd()*1024,r=between(.4,4);tc.fillStyle=['#a2ad7a','#71885f','#bec298','#8f9e6c'][i%4];tc.globalAlpha=.2;tc.beginPath();tc.ellipse(x,y,r,r*.5,0,0,7);tc.fill();}tc.globalAlpha=1;const terrainTexture=new T.CanvasTexture(terrainCanvas);terrainTexture.colorSpace=T.SRGBColorSpace;terrainTexture.anisotropy=renderer.capabilities.getMaxAnisotropy();floor.material=new T.MeshStandardMaterial({map:terrainTexture,color:'#d3ddb3',roughness:1});
const sky=mesh(new T.SphereGeometry(180,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color('#4f8fba')},bottom:{value:new T.Color('#e4d9b1')}},vertexShader:'varying vec3 vPosition;void main(){vPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPosition;void main(){float t=smoothstep(-5.0,110.0,vPosition.y);gl_FragColor=vec4(mix(bottom,top,t),1.0);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}' }));sky.castShadow=false;sky.receiveShadow=false;
for(let i=0;i<16;i++){const a=i/16*Math.PI*2;const cloud=new T.Group();scene.add(cloud);cloud.position.set(Math.sin(a)*85,between(18,32),Math.cos(a)*85);for(let j=0;j<5;j++){const puff=ball(between(4,8),new T.MeshBasicMaterial({color:'#ebeee0',transparent:true,opacity:.72}),j*5,between(-1,1),0,cloud,.28);puff.castShadow=false;}}
const waterRings=[];for(let i=0;i<6;i++){const r=ring(1+i*.6,'#c1ece0',-13,3,.075);r.scale.y=.65;waterRings.push(r);}
for(let i=0;i<22;i++){const x=between(-28,28),z=between(-28,28);if(Math.abs(x)<5||Math.hypot(x,z)>31)continue;const flower=new T.Group();scene.add(flower);flower.position.set(x,0,z);for(let j=0;j<4;j++){let a=j*1.57;ball(.11,i%2?'#e8bfd5':'#e9d8a2',Math.cos(a)*.14,.35,Math.sin(a)*.14,flower,.6);}cyl(.02,.025,.3,'#496e48',0,.15,0,flower,5);}
// Character: robe, belt, hair, articulated sleeves, long spirit sword.
function human(){const p=new T.Group();scene.add(p);cyl(.32,.62,1.1,'#e6e7ce',0,.8,0,p,12);const robe=cyl(.38,.32,.6,'#397f83',0,1.65,0,p,12);box(.73,.12,.47,'#c5a566',0,1.31,0,p);box(.18,.87,.08,'#4b9594',0,.83,.51,p);ball(.28,'#ecd3b3',0,2.12,0,p,1.1);ball(.3,'#31464b',0,2.25,-.05,p,.7);ball(.16,'#31464b',0,2.5,-.12,p);const tail=box(.14,.75,.17,'#35494d',0,1.88,-.28,p);tail.rotation.x=-.2;const arms=[];for(let s of [-1,1]){const arm=new T.Group();arm.position.set(s*.43,1.72,0);p.add(arm);cyl(.16,.25,.7,'#dce2cb',0,-.24,0,arm,8);ball(.12,'#ecd3b3',0,-.62,0,arm);arms.push(arm);}const sword=new T.Group();arms[1].add(sword);sword.position.set(0,-.64,.15);box(.08,.1,1.55,'#d5f0df',0,0,.6,sword);const tip=mesh(new T.ConeGeometry(.095,.35,4),'#e4ffff',0,0,1.52,sword);tip.rotation.x=Math.PI/2;box(.45,.09,.12,'#d7b775',0,0,0,sword);for(let side of [-1,1]){ball(.035,'#273943',side*.1,2.13,.258,p,.6);box(.19,.25,.34,'#3e5151',side*.23,.16,.1,p);const shoulder=ball(.19,'#d4c58a',side*.41,1.8,0,p,.55);}
box(.06,.59,.07,'#e4d6a1',0,1.65,.33,p);const beltGem=ball(.1,'#dcf8d6',0,1.32,.27,p);const staff=new T.Group();arms[1].add(staff);staff.position.set(0,-.52,.12);cyl(.045,.05,2.5,'#7e6750',0,.65,0,staff,8);const staffOrb=ball(.19,new T.MeshBasicMaterial({color:'#b39aed'}),0,2,0,staff);const spearTip=mesh(new T.ConeGeometry(.12,.55,4),'#f6d79c',0,2,0,staff);const halo=mesh(new T.TorusGeometry(.23,.028,6,20),'#dcc88b',0,1.95,0,staff);staff.visible=false;p.userData={arms,sword,robe,staff,staffOrb,spearTip};return p;}
const player=human();player.position.set(0,0,8);player.rotation.y=Math.PI;const playerRing=ring(.82,'#e0ce8d',0,8);
function fox(){const p=new T.Group();scene.add(p);const body=ball(.38,'#efd6ae',0,.52,0,p,.8);ball(.27,'#f5e4c6',0,.68,.35,p);for(let s of [-1,1]){const ear=mesh(new T.ConeGeometry(.14,.4,4),'#dba479',s*.16,.98,.3,p);ball(.04,'#344b48',s*.13,.73,.57,p);box(.09,.3,.1,'#b88865',s*.2,.2,.15,p);}const tail=ball(.33,'#f3dfbb',0,.7,-.55,p,1.6);tail.rotation.x=-.6;return p;}const pet=fox();pet.position.set(-1,0,9);
const enemies=[],effects=[],floaters=[],keys={};let running=false,started=false,time=0,zoom=1,hp=100,mp=100,kills=0,level=1,xp=0,won=false,boss=null,destination=null,selected=null,attackAnim=0,toastTimer=0;
const cds=[0,0,0],maxCds=[.5,5,9];
const CLASSES={
 sword:{name:'Espadachim',path:'CAMINHO DO JADE',color:'#5ab6aa',range:3.3,damage:23,armor:1,regen:5,skills:['Corte de jade','Dança das lâminas','Lótus vital'],icons:['⚔','✺','❀'],costs:[0,22,25],cooldowns:[.48,4.5,8],area:5.2,aoe:44,heal:45},
 mage:{name:'Arcanista',path:'CAMINHO DAS ESTRELAS',color:'#b39aed',range:12,damage:26,armor:1.2,regen:7,skills:['Orbe astral','Nova espiritual','Fonte lunar'],icons:['✧','✵','☽'],costs:[0,30,28],cooldowns:[.8,6,9],area:4.5,aoe:58,heal:40},
 guardian:{name:'Guardião solar',path:'CAMINHO DO SOL',color:'#edb460',range:3.8,damage:29,armor:.72,regen:5,skills:['Lança solar','Impacto do sol','Égide dourada'],icons:['♜','☀','◈'],costs:[0,25,30],cooldowns:[.8,6,11],area:4.5,aoe:48,heal:30}
};
let classId='sword',profileName='',profileSaved=false,shieldTime=0,combo=0,comboTimer=0;
let browserStorage;try{browserStorage=window.localStorage;}catch(e){browserStorage={getItem(){throw e;},setItem(){throw e;}};}
const characterStore=new JadeStorage.CharacterStore(browserStorage);
let selectedSlot=-1,activeSlot=-1,menuMode='roster',saveTimer=0,saveRequested=false,lastSaveAt=0;
const START_ENEMIES=[[8,2],[14,-5],[7,-9],[-8,-5],[-12,-14]];
const shieldVisual=mesh(new T.SphereGeometry(1.3,24,16),new T.MeshBasicMaterial({color:'#ffd586',transparent:true,opacity:.13,wireframe:true,depthWrite:false}));shieldVisual.visible=false;shieldVisual.castShadow=false;const config=()=>CLASSES[classId];const nextXP=()=>100+(level-1)*50;
let camDistance=30,camYaw=.48,camPitch=.72,camMode=0,dragging=false,lastPointer=null;
const camRay=new T.Raycaster(),camAim=new T.Vector3(),camWanted=new T.Vector3();
function setDistance(d){camDistance=T.MathUtils.clamp(d,4,44);camPitch=T.MathUtils.lerp(.13,.85,(camDistance-4)/40);$('cameraRange').value=camDistance;camMode=camDistance<9?2:camDistance<21?1:0;$('cameraBtn').querySelector('span').textContent=['Clássica','Aventura','Terceira pessoa'][camMode];document.body.classList.toggle('closeCamera',camMode===2);}
function cycleCamera(){const mode=(camMode+1)%3;setDistance([30,15,5.5][mode]);}
$('cameraBtn').onclick=cycleCamera;$('cameraRange').oninput=e=>setDistance(Number(e.target.value));
function awardXP(amount){xp+=amount;while(xp>=nextXP()){xp-=nextXP();level++;hp=100;mp=100;toast('Cultivo elevado · Nível '+level);burst(player.position.x,player.position.z,'#ffdf89',36);} }
function applyClass(){const c=config();maxCds.splice(0,3,...c.cooldowns);$('playerName').textContent=profileName||'Novo discípulo';$('classTitle').textContent=c.name.toUpperCase()+' · '+c.path;
document.querySelectorAll('[data-class]').forEach(b=>{b.classList.toggle('selected',b.dataset.class===classId);b.setAttribute('aria-pressed',b.dataset.class===classId?'true':'false');});
$('classSummary').textContent=c.name+' · '+c.skills.join(' / ');
document.querySelectorAll('[data-skill]').forEach((b,i)=>{b.querySelector('span').textContent=c.skills[i];b.querySelector('b').textContent=c.icons[i];b.title=`${i+1} — ${c.skills[i]} | ${c.costs[i]} energia | ${c.cooldowns[i]}s recarga`;});
if(player.userData.customRobe)player.userData.robe.material.dispose();player.userData.customRobe=true;player.userData.robe.material=new T.MeshStandardMaterial({color:c.color,roughness:.5});player.userData.sword.visible=classId==='sword';player.userData.staff.visible=classId!=='sword';player.userData.staffOrb.material.color.set(c.color);player.userData.staffOrb.visible=classId==='mage';player.userData.spearTip.visible=classId==='guardian';
}
document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{if(menuMode!=='create')return;classId=b.dataset.class;applyClass();});
function renderSlots(){const wrap=$('slotCards');wrap.replaceChildren();characterStore.data.slots.forEach((slot,i)=>{const button=document.createElement('button');button.className='slotCard'+(selectedSlot===i?' chosen':'')+(slot?' occupied':' empty');button.dataset.slot=i;button.setAttribute('aria-pressed',selectedSlot===i?'true':'false');const number=document.createElement('small');number.textContent='VAGA 0'+(i+1);const icon=document.createElement('span');icon.className='slotIcon';icon.textContent=slot?CLASSES[slot.classId].icons[0]:'＋';const title=document.createElement('b');title.textContent=slot?slot.name:'Criar personagem';const detail=document.createElement('p');detail.textContent=slot?CLASSES[slot.classId].name+' · Nível '+slot.state.level:'Um novo caminho espera por você.';const status=document.createElement('div');status.className='slotProgress';const dead=slot?.state.enemies?.filter(e=>e.id<5&&!e.alive).length||0;status.textContent=slot?(slot.state.enemies?.some(e=>e.id===5&&!e.alive)?'✧ Vale restaurado':dead+' / 5 espíritos purificados'):'Vaga disponível';button.append(number,icon,title,detail,status);button.onclick=()=>{selectedSlot=i;$('deleteConfirm').hidden=true;if(!slot){menuMode='create';classId='sword';profileName='';$('nameInput').value='';$('roster').hidden=true;$('creationFields').hidden=false;$('backToSlots').hidden=false;$('classSummary').hidden=false;$('introText').textContent='Criar personagem na vaga '+(i+1)+'. As outras vagas permanecem guardadas.';$('start').disabled=false;$('start').innerHTML='Criar e entrar no vale <span>→</span>';$('profileStatus').textContent='Escolha um nome com 2 a 20 caracteres.';applyClass();$('nameInput').focus();}else{renderSlots();$('start').disabled=false;$('start').innerHTML='Jogar com '+escapeText(slot.name)+' <span>→</span>';}};wrap.append(button);});$('deleteSlot').disabled=selectedSlot<0||!characterStore.data.slots[selectedSlot];$('rosterStatus').textContent=characterStore.warning||'Escolha um personagem para continuar ou uma vaga vazia para criar.';}
function escapeText(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function showRoster(){running=false;started=false;activeSlot=-1;selectedSlot=-1;menuMode='roster';keysClear();selected=null;destination=null;$('target').hidden=true;$('enemyFloat').hidden=true;$('modal').style.display='grid';$('modal').classList.remove('paused');$('roster').hidden=false;$('creationFields').hidden=true;$('backToSlots').hidden=true;$('classSummary').hidden=true;$('pauseActions').hidden=true;$('deleteConfirm').hidden=true;$('restoreConfirm').hidden=true;toastTimer=0;$('toast').style.opacity=0;$('introText').textContent='Três vagas. Cada personagem guarda sua própria história e evolução.';$('start').disabled=true;$('start').innerHTML='Selecione uma das três vagas <span>→</span>';renderSlots();}
function snapshot(){return {level,xp,hp,mp,position:{x:player.position.x,z:player.position.z},rotation:player.rotation.y,cooldowns:[...cds],shieldTime,camDistance,camYaw,camPitch,enemies:enemies.map(e=>({id:e.id,alive:e.alive,hp:e.hp,x:e.g.position.x,z:e.g.position.z}))};}
function saveCharacter(manual=false){if(activeSlot<0)return false;const previous=characterStore.data.slots[activeSlot];const ok=characterStore.set(activeSlot,{...previous,name:profileName,classId,updatedAt:Date.now(),state:snapshot()});profileSaved=ok;saveTimer=0;saveRequested=false;lastSaveAt=Date.now();$('saveStatus').textContent=ok?'✓ '+profileName+' · salvo às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'⚠ Falha ao salvar · baixe um backup no menu';$('saveStatus').classList.toggle('saveError',!ok);if(manual){const message=ok?'Progresso de '+profileName+' salvo.':characterStore.warning;if(menuMode==='pause')$('introText').textContent=message;else toast(message);}return ok;}
function clearTransient(){for(const e of effects)disposeEffect(e.m);effects.length=0;for(const f of floaters)disposeEffect(f.m);floaters.length=0;selected=null;destination=null;marker.visible=false;attackAnim=0;combo=0;comboTimer=0;}
function clearEnemies(){for(const e of enemies){scene.remove(e.g,e.aura);e.g.traverse(o=>{if(!o.isSprite)o.geometry?.dispose();if(o.isMesh&&!Array.from(mats.values()).includes(o.material))o.material.dispose();if(o.isSprite){o.material.map?.dispose();o.material.dispose();}});e.aura.geometry.dispose();e.aura.material.dispose();}enemies.length=0;boss=null;}
function updateQuest(){if(won){$('questText').textContent='Você restaurou a paz no Vale de Jade.';$('questProgress').textContent='Jornada concluída · Guardião purificado';$('questHint').textContent='Seu progresso está salvo. Explore o vale livremente.';}else if(kills===5){$('questText').textContent='Purifique o Guardião da névoa.';$('questProgress').textContent='Guardião · ao norte, diante do templo';$('questHint').textContent='Use '+config().skills[1]+' e '+config().skills[2]+'.';}else{$('questText').textContent='Purifique os 5 espíritos corrompidos.';$('questProgress').textContent='Espíritos purificados · '+kills+' / 5';$('questHint').textContent='TAB seleciona um inimigo próximo. Clique para persegui-lo.';}$('questBar').style.width=kills/5*100+'%';}
function enterSlot(i){const slot=characterStore.data.slots[i];if(!slot)return;clearTransient();clearEnemies();const st=slot.state;activeSlot=i;classId=slot.classId;profileName=slot.name;level=st.level;xp=st.xp;hp=st.hp;mp=st.mp;shieldTime=st.shieldTime;cds.splice(0,3,...st.cooldowns);player.position.set(st.position.x,0,st.position.z);if(!legal(player.position.x,player.position.z))player.position.set(0,0,8);player.rotation.y=st.rotation;pet.position.copy(player.position).add(new T.Vector3(-1,0,1));START_ENEMIES.forEach((pos,id)=>{const e=spawn(...pos,false,id);const saved=st.enemies?.find(n=>n.id===id);if(saved){e.alive=saved.alive&&saved.hp>0;e.hp=e.alive?saved.hp:0;if(e.alive)e.g.position.set(saved.x,0,saved.z);else scene.remove(e.g,e.aura);}});kills=enemies.filter(e=>!e.alive).length;won=false;if(kills===5){boss=spawn(0,-15,true,5);const saved=st.enemies?.find(e=>e.id===5);if(saved){boss.alive=saved.alive&&saved.hp>0;boss.hp=boss.alive?saved.hp:0;boss.g.position.set(saved.x,0,saved.z);if(!boss.alive){scene.remove(boss.g,boss.aura);won=true;}}}setDistance(st.camDistance);camYaw=st.camYaw;camPitch=st.camPitch;applyClass();updateQuest();running=true;started=true;menuMode='playing';$('modal').style.display='none';clock.getDelta();saveTimer=0;saveRequested=true;hud();toast('Bem-vindo ao vale, '+profileName+'.');}
$('backToSlots').onclick=showRoster;
$('switchCharacter').onclick=()=>{saveCharacter();clearTransient();showRoster();};$('saveNow').onclick=()=>saveCharacter(true);
$('exportSave').onclick=()=>{if(activeSlot>=0)saveCharacter();const blob=new Blob([characterStore.export()],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Vale-de-Jade-personagens.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let pendingRestore=null;
$('importSave').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>1000000)throw Error('large');pendingRestore=JadeStorage.parse(await file.text());const names=pendingRestore.slots.filter(Boolean).map(s=>s.name);$('restoreQuestion').textContent='Este backup contém '+names.length+' personagem(ns): '+(names.join(', ')||'nenhum')+'. Restaurar substituirá as três vagas atuais. Baixe um backup antes se quiser preservá-las.';$('restoreConfirm').hidden=false;}catch(err){pendingRestore=null;$('rosterStatus').textContent='Backup inválido. Selecione um arquivo de personagens do Vale de Jade 0.3. Suas vagas não foram alteradas.';}};
$('cancelRestore').onclick=()=>{pendingRestore=null;$('restoreConfirm').hidden=true;};$('confirmRestore').onclick=()=>{if(!pendingRestore)return;characterStore.data=pendingRestore;characterStore.blocked=false;characterStore.warning='';const ok=characterStore.persist();pendingRestore=null;showRoster();$('rosterStatus').textContent=ok?'Backup restaurado. Selecione seu personagem.':characterStore.warning;};
$('deleteSlot').onclick=()=>{if(selectedSlot<0)return;$('deleteQuestion').textContent='Excluir '+characterStore.data.slots[selectedSlot].name+' e todo o progresso desta vaga?';$('deleteConfirm').hidden=false;};$('cancelDelete').onclick=()=>$('deleteConfirm').hidden=true;$('confirmDelete').onclick=()=>{characterStore.remove(selectedSlot);showRoster();};
window.addEventListener('pagehide',()=>saveCharacter());window.addEventListener('beforeunload',()=>saveCharacter());

function label(text,color='#ffffff'){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d');ctx.font='28px Georgia';ctx.textAlign='center';ctx.shadowColor='#14343c';ctx.shadowBlur=6;ctx.fillStyle=color;ctx.fillText(text,256,43);const m=new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true,depthTest:false});const sprite=new T.Sprite(m);sprite.scale.set(4.6,.72,1);return sprite;}
function spawn(x,z,isBoss=false,id=isBoss?5:enemies.length){const g=new T.Group();scene.add(g);g.position.set(x,0,z);const c=isBoss?'#826679':'#9697c0';ball(.64,c,0,1,0,g,1.18);const head=ball(.45,isBoss?'#ae817f':'#c6bfd6',0,1.65,0,g);for(let s of [-1,1]){const horn=mesh(new T.ConeGeometry(.14,.65,5),'#dfc6aa',s*.34,2.13,0,g);horn.rotation.z=-s*.4;ball(.085,new T.MeshBasicMaterial({color:isBoss?'#ffc375':'#e6eea6'}),s*.18,1.72,.39,g);const arm=ball(.24,c,s*.65,1,0,g,1.7);arm.rotation.z=s*.4;}const aura=ring(isBoss?1.5:.8,isBoss?'#e9ab74':'#a6a0d9',x,z);if(isBoss)g.scale.setScalar(1.65);const max=isBoss?280:64;const e={id,g,aura,hp:max,max,x,z,boss:isBoss,hit:0,atk:1,alive:true};const tag=label(isBoss?'Guardião da névoa':'Espírito inquieto',isBoss?'#ffdfac':'#f2e8f5');tag.position.y=2.6;g.add(tag);e.tag=tag;enemies.push(e);return e;}
START_ENEMIES.forEach((p,id)=>spawn(...p,false,id));
const ray=new T.Raycaster(),mouse=new T.Vector2(),ground=new T.Plane(new T.Vector3(0,1,0),0),hit=new T.Vector3();
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;toastTimer=3.2;$('message').textContent=s;}
let audio=null,sound=false;function tone(f,d=.12){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.7,audio.currentTime+d);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch(e){sound=false;}}
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=64;const gc=glowCanvas.getContext('2d'),gradient=gc.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.15,'rgba(255,255,255,.95)');gradient.addColorStop(.45,'rgba(255,255,255,.3)');gradient.addColorStop(1,'rgba(255,255,255,0)');gc.fillStyle=gradient;gc.fillRect(0,0,64,64);const glowTexture=new T.CanvasTexture(glowCanvas);
function glow(color,x,y,z,size=.4){const m=new T.Sprite(new T.SpriteMaterial({map:glowTexture,color,transparent:true,blending:T.AdditiveBlending,depthWrite:false}));m.position.set(x,y,z);m.scale.setScalar(size);scene.add(m);return m;}
function addFX(m,life,extra={}){m.castShadow=false;effects.push({m,life,max:life,baseOpacity:m.material.opacity??1,baseScale:m.scale.clone(),...extra});return m;}
function burst(x,z,color,n=18,y=.9){for(let i=0;i<n;i++){const m=glow(color,x,y,z,between(.13,.4));addFX(m,between(.45,.95),{v:new T.Vector3(between(-3.5,3.5),between(1,4),between(-3.5,3.5)),gravity:2});}}
function magicCircle(x,z,color,r=3){for(let k=0;k<2;k++){const m=mesh(new T.RingGeometry(r-.07-k*.35,r-k*.35,64),new T.MeshBasicMaterial({color,transparent:true,opacity:.9,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false}),x,.13+k*.02,z);m.rotation.x=-Math.PI/2;addFX(m,1,{grow:.2,spin:k?-.7:.7});}for(let j=0;j<10;j++){const a=j*Math.PI/5;const rune=mesh(new T.OctahedronGeometry(.13),new T.MeshBasicMaterial({color,transparent:true,blending:T.AdditiveBlending}),x+Math.sin(a)*r,.28,z+Math.cos(a)*r);addFX(rune,.9,{v:new T.Vector3(0,.8,0),spin:2});}}
function wave(r,color){magicCircle(player.position.x,player.position.z,color,r*.55);}
function healFX(){const c=config().color;magicCircle(player.position.x,player.position.z,c,1.7);for(let i=0;i<18;i++){const a=i*Math.PI/9;const m=glow(c,player.position.x+Math.cos(a)*.8,.2,player.position.z+Math.sin(a)*.8,.4);addFX(m,1.35,{orbit:{x:player.position.x,z:player.position.z,a,r:.85},v:new T.Vector3(0,1.8,0)});}}
function novaFX(x,z){const c=config().color;magicCircle(x,z,c,config().area);burst(x,z,c,32,1.1);if(classId==='mage'){const dome=mesh(new T.SphereGeometry(1,24,12),new T.MeshBasicMaterial({color:c,transparent:true,opacity:.22,wireframe:true,blending:T.AdditiveBlending,depthWrite:false}),x,1,z);addFX(dome,.65,{grow:4});for(let i=0;i<4;i++){const halo=mesh(new T.TorusGeometry(1.2,.04,6,48),new T.MeshBasicMaterial({color:'#e1d6ff',transparent:true,blending:T.AdditiveBlending}),x,1.3,z);halo.rotation.set(i*.7,i,0);addFX(halo,.8,{grow:2.6,spin:3});}}else if(classId==='guardian'){for(let i=0;i<12;i++){let a=i*Math.PI/6;const flame=glow('#ffbb53',x+Math.sin(a)*2,.4,z+Math.cos(a)*2,1.1);addFX(flame,.9,{v:new T.Vector3(Math.sin(a)*2,3,Math.cos(a)*2),gravity:2});}}else{for(let i=0;i<3;i++){const blade=mesh(new T.TorusGeometry(1.8+i*.3,.055,6,48,Math.PI*1.55),new T.MeshBasicMaterial({color:c,transparent:true,blending:T.AdditiveBlending}),x,.7+i*.45,z);blade.rotation.set(Math.PI/2,.15,i*2);addFX(blade,.65,{grow:1.4,spin:8});}}}
function damage(e,n){if(!e.alive)return;e.hp=Math.max(0,e.hp-n);e.hit=.2;saveRequested=true;burst(e.g.position.x,e.g.position.z,e.boss?'#f3c685':'#c9b9ef',10);const f=label(String(n),'#fff0b9');f.scale.set(2,.5,1);f.position.copy(e.g.position);f.position.y=3;scene.add(f);floaters.push({m:f,life:.9});if(e.hp<=0){e.alive=false;scene.remove(e.g,e.aura);if(selected===e){selected=null;destination=null;}awardXP(e.boss?100:35);if(e.boss){won=true;toast('O vale floresce outra vez. Jornada concluída!');$('questText').textContent='Você restaurou a paz no Vale de Jade.';$('questProgress').textContent='Jornada concluída · Guardião purificado';$('questHint').textContent='Seu progresso está salvo. Explore livremente.';$('questBar').style.width='100%';tone(880,.8);}else{kills++;$('questProgress').textContent=`Espíritos purificados · ${kills} / 5`;$('questBar').style.width=(kills/5*100)+'%';if(kills===5){boss=spawn(0,-15,true);$('questText').textContent='Purifique o Guardião da névoa.';$('questProgress').textContent='Guardião · ao norte, diante do templo';$('questHint').textContent='Use '+config().skills[1]+' e '+config().skills[2]+'.';toast('O Guardião despertou. Vá ao templo!');}else toast(`Espírito purificado · ${kills} de 5`);}}}
function distanceTo(e){return Math.hypot(e.g.position.x-player.position.x,e.g.position.z-player.position.z);}
function slash(color){for(let i=0;i<3;i++){const m=mesh(new T.TorusGeometry(1.45+i*.18,.065-i*.015,6,36,Math.PI*1.3),new T.MeshBasicMaterial({color:i===0?'#fff7cc':color,transparent:true,opacity:1-i*.22,blending:T.AdditiveBlending,depthWrite:false}),player.position.x,player.position.y+1.15,player.position.z);m.rotation.set(Math.PI/2,.25,player.rotation.y+i*.15);addFX(m,.35+i*.06,{grow:.4,spin:4});}}
function projectile(e,n){const m=glow(config().color,player.position.x,player.position.y+1.5,player.position.z,.85);addFX(m,2,{target:e,damage:n,trail:0});}
function skill(i){if(!running||cds[i]>0)return;const c=config();if(mp<c.costs[i]){toast('É preciso '+c.costs[i]+' de energia. Ela se recupera sozinha.');return;}
if(i===2){if(hp>=100&&classId!=='guardian'){toast('Sua vida já está completa.');return;}mp-=c.costs[i];hp=Math.min(100,hp+c.heal);shieldTime=classId==='guardian'?5:0;cds[i]=maxCds[i];healFX();burst(player.position.x,player.position.z,c.color,16);tone(660,.4);toast(classId==='guardian'?'Égide ativa · 65% de proteção por 5s':'Vida restaurada · +'+c.heal);return;}
const reach=i===0?c.range:classId==='mage'?14:c.area;const nearby=enemies.filter(e=>e.alive&&distanceTo(e)<=reach).sort((a,b)=>distanceTo(a)-distanceTo(b));if(!nearby.length){toast('Nenhum espírito ao alcance ('+reach+' m).');return;}
if(selected?.alive&&!nearby.includes(selected)){toast('Seu alvo está fora do alcance. Aproxime-se ou pressione TAB.');return;}const target=selected?.alive?selected:nearby[0];selected=target;mp-=c.costs[i];cds[i]=maxCds[i];attackAnim=.35;player.rotation.y=Math.atan2(target.g.position.x-player.position.x,target.g.position.z-player.position.z);
if(i===0){if(comboTimer<=0)combo=0;combo=classId==='sword'?(combo+1)%3:1;comboTimer=2;const n=c.damage+(level-1)*4+(classId==='sword'&&combo===0?12:0);if(classId==='mage')projectile(target,n);else{damage(target,n);slash(c.color);}tone(classId==='mage'?580:350);}
else{const center=classId==='mage'?target.g.position:player.position;const x=center.x,z=center.z;for(const e of enemies.filter(e=>e.alive&&Math.hypot(e.g.position.x-x,e.g.position.z-z)<=c.area))damage(e,c.aoe+(level-1)*5);novaFX(x,z);tone(520,.35);}}
function pause(){running=false;keysClear();saveCharacter();menuMode='pause';$('modal').style.display='grid';$('roster').hidden=true;$('creationFields').hidden=true;$('backToSlots').hidden=true;$('classSummary').hidden=false;$('pauseActions').hidden=false;$('introText').textContent='Jornada em pausa · '+profileName+' · '+config().name;$('modal').classList.add('paused');$('start').disabled=false;$('start').innerHTML='Continuar jornada <span>→</span>';}
function keysClear(){for(const k in keys)keys[k]=false;dragging=false;}
$('start').onclick=()=>{if(menuMode==='pause'){running=true;menuMode='playing';$('modal').style.display='none';clock.getDelta();return;}if(menuMode==='roster'){if(selectedSlot>=0)enterSlot(selectedSlot);return;}if(menuMode==='create'){const name=$('nameInput').value.trim().replace(/\s+/g,' ');if(name.length<2||name.length>20){$('profileStatus').textContent='Digite um nome com 2 a 20 caracteres.';$('nameInput').focus();return;}if(selectedSlot<0||characterStore.data.slots[selectedSlot])return;const slot={id:crypto.randomUUID?crypto.randomUUID():'character-'+Date.now(),name,classId,createdAt:Date.now(),updatedAt:Date.now(),state:{}};characterStore.set(selectedSlot,slot);enterSlot(selectedSlot);}};
$('helpBtn').onclick=pause;$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').querySelector('span').textContent=sound?'Som ligado':'Som desligado';tone(620,.3);};document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>skill(Number(b.dataset.skill)));
window.addEventListener('keydown',e=>{if(e.target.matches('input:not([type=range]),textarea'))return;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();const k=e.key.toLowerCase();keys[k]=true;if(e.repeat)return;if(k==='v'&&running)cycleCamera();if(k==='h'||k==='escape'){if(running)pause();else if(menuMode==='pause')$('start').click();else if(menuMode==='create')showRoster();}if(k==='tab'&&running){e.preventDefault();cycleTarget();}if(k===' '||k==='1')skill(0);if(k==='2')skill(1);if(k==='3')skill(2);});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{keysClear();if(running)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();});
renderer.domElement.addEventListener('pointerdown',e=>{if(!running||e.button!==0)return;mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(mouse,camera);const alive=enemies.filter(x=>x.alive);const intersections=ray.intersectObjects(alive.map(x=>x.g),true);selected=null;if(intersections.length){let o=intersections[0].object;while(o.parent&&o.parent!==scene)o=o.parent;selected=alive.find(x=>x.g===o);if(selected)destination=selected.g.position.clone();}else if(ray.ray.intersectPlane(ground,hit)&&Math.hypot(hit.x,hit.z)<35){destination=hit.clone();marker.position.set(hit.x,.12,hit.z);marker.visible=true;}});
renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===2&&running){dragging=true;lastPointer={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);}});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;camYaw-=(e.clientX-lastPointer.x)*.006;camPitch=T.MathUtils.clamp(camPitch+(e.clientY-lastPointer.y)*.004,.06,1.25);lastPointer={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('lostpointercapture',()=>dragging=false);
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(running)setDistance(camDistance+e.deltaY*.015);},{passive:false});const marker=ring(.55,'#f2dfa0',0,0);marker.visible=false;
function legal(x,z){if(Math.hypot(x,z)>35)return false;if((x+13)**2/55+(z-3)**2/26<1&&Math.abs(z-3)>1.05)return false;return !obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+.35);}
function move(dx,dz){let x=player.position.x+dx,z=player.position.z+dz;if(legal(x,z)){player.position.x=x;player.position.z=z;}else{if(legal(x,player.position.z))player.position.x=x;if(legal(player.position.x,z))player.position.z=z;}if(dx||dz)player.rotation.y=Math.atan2(dx,dz);}
function respawn(){hp=100;mp=100;destination=null;selected=null;player.position.set(0,0,8);for(const e of enemies.filter(e=>e.alive)){e.g.position.set(e.x,0,e.z);e.hp=e.max;}toast('O santuário restaurou suas forças. Tente novamente.');}
function disposeEffect(m){scene.remove(m);if(!m.isSprite)m.geometry?.dispose();if(m.material.map&&m.material.map!==glowTexture)m.material.map.dispose();m.material.dispose();}
const petalGeo=new T.BufferGeometry(),petalPos=[];for(let i=0;i<120;i++)petalPos.push(between(-30,30),between(1,13),between(-30,30));petalGeo.setAttribute('position',new T.Float32BufferAttribute(petalPos,3));const petals=new T.Points(petalGeo,new T.PointsMaterial({color:'#ffe1df',size:.12,transparent:true,opacity:.8}));scene.add(petals);
const map=$('map').getContext('2d');function minimap(){map.clearRect(0,0,170,170);map.fillStyle='#31594e';map.fillRect(0,0,170,170);map.fillStyle='#79937a';map.beginPath();map.arc(85,85,73,0,7);map.fill();map.strokeStyle='#c9c7a0';map.lineWidth=5;map.beginPath();map.moveTo(85,32);map.lineTo(85,144);map.stroke();map.fillStyle='#6bb1ad';map.beginPath();map.ellipse(58,91,15,10,0,0,7);map.fill();map.fillStyle='#f0d29b';map.fillRect(77,34,16,10);for(const e of enemies.filter(e=>e.alive)){map.fillStyle=e.boss?'#ffc36f':'#d8b7f3';map.beginPath();map.arc(85+e.g.position.x*2.1,85+e.g.position.z*2.1,e.boss?4:3,0,7);map.fill();}map.fillStyle='#fff5c7';map.beginPath();map.arc(85+player.position.x*2.1,85+player.position.z*2.1,4,0,7);map.fill();}
$('clearTarget').onclick=()=>{selected=null;destination=null;hud();};
function cycleTarget(){const list=enemies.filter(e=>e.alive&&distanceTo(e)<28).sort((a,b)=>distanceTo(a)-distanceTo(b));if(!list.length){toast('Nenhum inimigo próximo.');return;}selected=list[(list.indexOf(selected)+1)%list.length];destination=null;hud();}
function targetHUD(){const e=selected?.alive?selected:null;$('target').hidden=!e;$('enemyFloat').hidden=true;for(const n of enemies){n.aura.material.color.set(n===e?'#ffe2a3':n.boss?'#e9ab74':'#a6a0d9');n.aura.material.opacity=n===e?.95:.35;}if(!e)return;const pct=e.hp/e.max*100;$('targetName').textContent=e.boss?'Guardião da névoa':'Espírito inquieto';$('targetKind').textContent=e.boss?'CHEFE · NÍVEL 3':'ESPÍRITO · NÍVEL 1';$('targetHP').style.width=pct+'%';$('targetHPText').textContent=Math.ceil(e.hp)+' / '+e.max+' PV';$('targetHP').parentElement.setAttribute('aria-valuenow',Math.round(pct));$('targetDistance').textContent=Math.ceil(distanceTo(e))+' m · '+(distanceTo(e)<=config().range?'Ao alcance':'Fora do alcance')+' · TAB para trocar';}
function floatingTarget(){if(!running||!selected?.alive){$('enemyFloat').hidden=true;return;}const v=selected.g.position.clone();v.y+=selected.boss?4.4:2.65;v.project(camera);const x=(v.x+1)*innerWidth/2,y=(1-v.y)*innerHeight/2;const visible=v.z>-1&&v.z<1&&x>40&&x<innerWidth-40&&y>120&&y<innerHeight-160;$('enemyFloat').hidden=!visible;if(visible){$('enemyFloat').style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;$('enemyFloatName').textContent=selected.boss?'Guardião da névoa':'Espírito inquieto';$('enemyFloatHP').style.width=(selected.hp/selected.max*100)+'%';}}
let hudTimer=0;function hud(){hp=Math.max(0,hp);$('hp').style.transform=`scaleX(${hp/100})`;$('mp').style.transform=`scaleX(${mp/100})`;$('hpText').textContent=`${Math.ceil(hp)} / 100`;$('mpText').textContent=`${Math.floor(mp)} / 100`;$('level').textContent='Nv. '+level;const progress=Math.min(100,xp/nextXP()*100);$('xp').style.width=progress+'%';$('xp').parentElement.setAttribute('aria-valuenow',Math.round(progress));$('xpText').textContent=`${xp} / ${nextXP()} EXP · Nível ${level} → ${level+1}`;$('rankTitle').textContent=['Primeiro despertar','Discípulo do vale','Cultivador do jade'][Math.min(level-1,2)]+(shieldTime>0?' · Égide '+Math.ceil(shieldTime)+'s':'');document.querySelectorAll('[data-skill]').forEach((b,i)=>{const em=b.querySelector('em');em.style.display=cds[i]>.05?'flex':'none';em.textContent=cds[i]<1?cds[i].toFixed(1):Math.ceil(cds[i]);b.classList.toggle('noEnergy',mp<config().costs[i]);});targetHUD();minimap();}
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);time+=dt;
if(running){saveTimer+=dt;for(let i=0;i<3;i++)cds[i]=Math.max(0,cds[i]-dt);mp=Math.min(100,mp+dt*config().regen);shieldTime=Math.max(0,shieldTime-dt);comboTimer=Math.max(0,comboTimer-dt);let dx=0,dz=0;let sx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),sy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(sx||sy){destination=null;marker.visible=false;dx=sx*Math.cos(camYaw)+sy*Math.sin(camYaw);dz=-sx*Math.sin(camYaw)+sy*Math.cos(camYaw);}else if(destination){if(selected?.alive)destination.copy(selected.g.position);let d=destination.clone().sub(player.position);d.y=0;if(d.length()>(selected?config().range*.8:.25)){dx=d.x;dz=d.z;}else{if(selected)skill(0);else{destination=null;marker.visible=false;}}}let moving=!!(dx||dz);if(moving){let len=Math.hypot(dx,dz);move(dx/len*dt*5.8,dz/len*dt*5.8);}player.position.y=Math.abs(player.position.x+13)<8&&Math.abs(player.position.z-3)<1.15?.35+Math.sin(T.MathUtils.clamp((player.position.x+22)/12.35,0,1)*Math.PI)*1.05:0;
attackAnim=Math.max(0,attackAnim-dt);player.userData.arms.forEach((a,i)=>a.rotation.x=attackAnim>0?-1.3+Math.sin(attackAnim*22)*.9:moving?Math.sin(time*12+i*Math.PI)*.4:Math.sin(time*2+i)*.045);
for(const e of enemies){if(!e.alive)continue;e.hit=Math.max(0,e.hit-dt);e.atk-=dt;const d=player.position.clone().sub(e.g.position);d.y=0;let distance=d.length();if(distance<(e.boss?11:8)&&distance>1.7){d.normalize();const speed=e.boss?1.8:2;e.g.position.addScaledVector(d,dt*speed);e.g.rotation.y=Math.atan2(d.x,d.z);}if(distance<2.3&&e.atk<=0){hp-=(e.boss?15:6)*config().armor*(shieldTime>0?.35:1);e.atk=e.boss?1.35:1.6;burst(player.position.x,player.position.z,'#f0b69e',5);tone(140,.12);if(hp<=0){respawn();break;}}e.g.position.y=Math.sin(time*2.5+e.x)*.13;e.g.rotation.z=e.hit>0?Math.sin(time*70)*.12:0;e.aura.position.x=e.g.position.x;e.aura.position.z=e.g.position.z;}
pet.position.lerp(new T.Vector3(player.position.x-1.2,player.position.y,player.position.z+1.3),dt*3);pet.rotation.y=player.rotation.y;pet.position.y+=Math.sin(time*8)*.04;
}
shieldVisual.visible=shieldTime>0;shieldVisual.position.copy(player.position).add(new T.Vector3(0,1.2,0));shieldVisual.rotation.y=time*.3;playerRing.position.set(player.position.x,player.position.y+.1,player.position.z);camAim.set(player.position.x,player.position.y+1.55,player.position.z);const offset=new T.Vector3(Math.sin(camYaw)*Math.cos(camPitch),Math.sin(camPitch),Math.cos(camYaw)*Math.cos(camPitch));let actualDistance=camDistance;camRay.set(camAim,offset);camRay.far=camDistance;const occlusion=camRay.intersectObjects(cameraOccluders,true);if(occlusion.length)actualDistance=Math.max(2,occlusion[0].distance-.45);camWanted.copy(camAim).addScaledVector(offset,actualDistance);camera.position.lerp(camWanted,1-Math.exp(-dt*(actualDistance<camDistance?18:9)));camera.position.y=Math.max(camera.position.y,.65);camera.lookAt(camAim);

const effectDt=running?dt:0;for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=effectDt;e.m.material.opacity=Math.max(0,e.life/e.max)*(e.baseOpacity??1);if(e.target&&running){if(!e.target.alive)e.life=0;else{const goal=e.target.g.position.clone().add(new T.Vector3(0,1.3,0));const delta=goal.sub(e.m.position);if(delta.length()<dt*22+.3){burst(goal.x,goal.z,config().color,12,goal.y);damage(e.target,e.damage);e.life=0;}else{e.m.position.addScaledVector(delta.normalize(),dt*22);e.trail=(e.trail||0)+dt;if(e.trail>.03){e.trail=0;addFX(glow(config().color,e.m.position.x,e.m.position.y,e.m.position.z,.35),.35);}}}}if(e.v){if(e.gravity)e.v.y-=e.gravity*effectDt;e.m.position.addScaledVector(e.v,effectDt);}if(e.orbit){e.orbit.a+=effectDt*4;e.m.position.x=e.orbit.x+Math.cos(e.orbit.a)*e.orbit.r;e.m.position.z=e.orbit.z+Math.sin(e.orbit.a)*e.orbit.r;}if(e.spin)e.m.rotation.z+=effectDt*e.spin;if(e.grow){if(e.baseScale)e.m.scale.copy(e.baseScale).multiplyScalar(1+(1-e.life/e.max)*e.grow);else e.m.scale.setScalar(1+(1-e.life/e.max)*e.grow);}if(e.life<=0){disposeEffect(e.m);effects.splice(i,1);}}
for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.life-=effectDt;f.m.position.y+=effectDt;f.m.material.opacity=Math.max(0,f.life);if(f.life<=0){disposeEffect(f.m);floaters.splice(i,1);}}
const pos=petalGeo.attributes.position;for(let i=0;i<pos.count;i++){pos.setY(i,pos.getY(i)-dt*.35);pos.setX(i,pos.getX(i)+Math.sin(time+i)*dt*.15);if(pos.getY(i)<.1)pos.setY(i,12);}pos.needsUpdate=true;pond.material.opacity=.88+Math.sin(time)*.025;waterRings.forEach((r,i)=>{const p=(time*.13+i/6)%1;r.scale.set(1+p*1.4,.65+p*.9,1);r.material.opacity=(1-p)*.22;});marker.rotation.z=time;toastTimer-=dt;if(toastTimer<=0)$('toast').style.opacity=0;hudTimer+=dt;if(hudTimer>.1){hud();hudTimer=0;}floatingTarget();if(running&&(saveRequested||saveTimer>3))saveCharacter();renderer.render(scene,camera);}
applyClass();setDistance(30);camera.position.set(15,23,30);showRoster();hud();frame();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// Read-only diagnostics for smoke checks and future iteration.
window.valeDeJade={getState:()=>({running,menuMode,activeSlot,selectedSlot,slots:characterStore.data.slots.map(s=>s?{name:s.name,classId:s.classId,level:s.state.level,xp:s.state.xp}:null),selectedEnemy:selected?.alive?{id:selected.id,hp:selected.hp,max:selected.max}:null,hp,mp,kills,level,xp,xpNeeded:nextXP(),classId,profileName,profileSaved,camDistance,camYaw,camPitch,shieldTime,cooldowns:[...cds],won,position:{x:player.position.x,z:player.position.z},enemies:enemies.filter(e=>e.alive).map(e=>({id:e.id,x:e.g.position.x,z:e.g.position.z,hp:e.hp,boss:e.boss,screen:(()=>{const v=e.g.position.clone();v.y+=1.2;v.project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};})()})),drawCalls:renderer.info.render.calls})};
})();





