/* Pure inventory and deterministic world rules. Shared by browser and tests. */
(function(root){'use strict';
const CATEGORIES={all:'Todos',weapon:'Armas',armor:'Armaduras',accessory:'Acessórios',consumable:'Consumíveis',material:'Materiais'};
const RARITIES={common:{name:'Comum',color:'#bdc8bf',factor:1},uncommon:{name:'Incomum',color:'#83d8ae',factor:1.25},rare:{name:'Raro',color:'#8ebeff',factor:1.65},epic:{name:'Épico',color:'#d4a1ff',factor:2.2}};
const ITEMS={
 sword:{name:'Espada',icon:'⚔',category:'weapon',slot:'weapon',classId:'sword'},staff:{name:'Cajado',icon:'✧',category:'weapon',slot:'weapon',classId:'mage'},spear:{name:'Lança',icon:'♜',category:'weapon',slot:'weapon',classId:'guardian'},grimoire:{name:'Grimório',icon:'☾',category:'weapon',slot:'weapon',classId:'summoner'},
 robe:{name:'Vestes',icon:'♜',category:'armor',slot:'armor'},amulet:{name:'Amuleto',icon:'◈',category:'accessory',slot:'accessory'},
 health:{name:'Elixir de vida',icon:'♥',category:'consumable',description:'Restaura 60 de vida. Não é consumido com vida cheia.'},mana:{name:'Elixir espiritual',icon:'✦',category:'consumable',description:'Restaura 65 de energia. Não é consumido com energia cheia.'},shard:{name:'Essência das trevas',icon:'⬡',category:'material',description:'Material obtido de criaturas. Pode ser guardado para futuras receitas.'}
};
const WEAPONS={sword:'sword',mage:'staff',guardian:'spear',summoner:'grimoire'};
const clamp=(v,a,b,d)=>typeof v==='number'&&Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;
function item(key,tier=0,rarity='common'){const base=ITEMS[key];if(!base||!RARITIES[rarity])return null;tier=Math.floor(clamp(tier,0,12,0));const gear=!!base.slot;if(!gear){tier=0;rarity='common';}const factor=RARITIES[rarity].factor,required=tier?Math.max(1,tier):1;return {...base,key,tier,rarity,id:key+':'+tier+':'+rarity,name:base.name+(gear?(tier?' de '+['Jade','Âmbar','Geada','Eclipse'][(tier-1)%4]+' +'+tier:' de aprendiz'):''),required,attack:gear&&base.slot==='weapon'?Math.round(tier*6*factor):0,defense:base.slot==='armor'?Math.round(tier*4*factor):0,spirit:base.slot==='accessory'?Math.round(tier*2*factor):0};}
function byId(id){if(typeof id!=='string')return null;const p=id.split(':');if(p.length!==3||!/^\d+$/.test(p[1]))return null;const it=item(p[0],Number(p[1]),p[2]);return it&&it.id===id?it:null;}
function starter(cls){const w=item(WEAPONS[cls]||'sword'),a=item('robe');return {items:[{id:w.id,qty:1},{id:a.id,qty:1},{id:item('health').id,qty:3},{id:item('mana').id,qty:2}],equipped:{weapon:w.id,armor:a.id,accessory:null},coins:0};}
function cleanInventory(raw,cls,level){if(!raw||!Array.isArray(raw.items))return starter(cls);const merged=new Map();for(const row of raw.items.slice(0,1000)){if(!row||!byId(row.id))continue;const qty=Math.floor(clamp(row.qty,0,999,0));if(qty)merged.set(row.id,Math.min(999,(merged.get(row.id)||0)+qty));}const items=Array.from(merged,([id,qty])=>({id,qty})).slice(0,60),equipped={};for(const slot of ['weapon','armor','accessory']){const it=byId(raw.equipped?.[slot]);equipped[slot]=it&&it.slot===slot&&(!it.classId||it.classId===cls)&&it.required<=level&&items.some(r=>r.id===it.id)?it.id:null;}return {items,equipped,coins:Math.floor(clamp(raw.coins,0,9999999,0))};}
function bonuses(bag){const gear=Object.values(bag.equipped).map(byId).filter(Boolean);return gear.reduce((s,it)=>({attack:s.attack+it.attack,defense:s.defense+it.defense,spirit:s.spirit+it.spirit}),{attack:0,defense:0,spirit:0});}
function hash(text){let n=2166136261;for(const c of String(text)){n^=c.charCodeAt(0);n=Math.imul(n,16777619);}return n>>>0||1;}
function random(seed){let n=seed>>>0;return ()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
const BIOMES=[{name:'Bosque Esmeralda',ground:'#658b67',leaf:'#458675',rock:'#86ad91',types:['wolf','spider']},{name:'Deserto de Âmbar',ground:'#b49d73',leaf:'#947c51',rock:'#d0ab6a',types:['spider','golem']},{name:'Jardins da Geada',ground:'#a7c2cd',leaf:'#739fad',rock:'#bde4e8',types:['wisp','wolf']},{name:'Terras do Eclipse',ground:'#685b80',leaf:'#695d90',rock:'#b494d3',types:['golem','wisp','spider']}];
function generateWorld(seed){const rand=random(seed),regions=[],bridges=[],foes=[];for(let row=1;row<=4;row++)for(let col=-1;col<=1;col++){const id=(row-1)*3+col+1,x=col*68,z=-row*76,r=31+rand()*2,biome=col===0?row-1:(row-1+Math.floor(rand()*2))%4,tier=2+row*2+Math.abs(col),region={id,x,z,r,row,col,biome,tier,name:BIOMES[biome].name+' '+['Ocidental','Central','Oriental'][col+1]+' · '+['I','II','III','IV'][row-1],decor:[]};regions.push(region);bridges.push({x1:x,z1:z,x2:x,z2:z+76});if(col<1)bridges.push({x1:x,z1:z,x2:x+68,z2:z});const count=4+row*2;for(let j=0;j<count;j++){const a=(j+.5)/count*Math.PI*2+rand()*.15,rr=14+rand()*10;let dx=Math.cos(a)*rr,dz=Math.sin(a)*rr;if(Math.abs(dx)<5)dx=Math.sign(dx||1)*6;if(Math.abs(dz)<5)dz=Math.sign(dz||1)*6;const elite=row===4&&j===count-1,type=elite?'colossus':BIOMES[biome].types[Math.floor(rand()*BIOMES[biome].types.length)],lv=tier+(j%3===0?1:0);foes.push({id:100+id*20+j,region:id,type,x:x+dx,z:z+dz,level:lv,max:Math.round((70+lv*26)*(elite?2:1)),power:Math.round(5+lv*2.1),reward:25+lv*11,elite});}for(let j=0;j<50;j++){const dx=(rand()-.5)*r*1.8,dz=(rand()-.5)*r*1.8;if(Math.hypot(dx,dz)>r-2||Math.abs(dx)<5||Math.abs(dz)<5||foes.some(e=>e.region===id&&Math.hypot(e.x-x-dx,e.z-z-dz)<2.2))continue;region.decor.push({x:dx,z:dz,size:.7+rand()*1.2,angle:rand()*Math.PI*2});}}
 return {seed,regions,bridges,foes};}
function onBridge(x,z,b,width=2.8){const dx=b.x2-b.x1,dz=b.z2-b.z1,len=dx*dx+dz*dz,t=Math.max(0,Math.min(1,((x-b.x1)*dx+(z-b.z1)*dz)/len));return Math.hypot(x-b.x1-dx*t,z-b.z1-dz*t)<width;}
const api={CATEGORIES,RARITIES,ITEMS,WEAPONS,item,byId,starter,cleanInventory,bonuses,hash,random,BIOMES,generateWorld,onBridge};root.JadeSystems=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
